"""The OCR workshop runs its model steps in a uv isolated environment.

No kernel install, no restart, hashed wheels only.

Static checks of the notebook, the carried stage file and the lock, plus the kernel/stage hand-off: the
runtime cell's own run_stage drives a real stage process, and the full stage sequence runs in-process with
model doubles (no torch, no network). Not execution evidence for a hosted runtime.
"""

import ast
import hashlib
import json
import os
import re
import subprocess
import sys
import types
from pathlib import Path

import build_ocr_workshop_carrier as carrier
import numpy as np
import ocr_workshop as stages
import pytest
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "tutorials" / "DIMER_OCR_Document_Extraction_Workshop.ipynb"
STAGE_FILE = ROOT / "tools" / "ocr_workshop.py"
LOCK = ROOT / "tools" / "ocr-workshop-requirements.lock"
REQUIREMENTS = ROOT / "tools" / "ocr-workshop-requirements.in"
RUNTIME_CELL = "f5cd762a"
FORMER_PINS = {
    "torch": "2.14.0", "torchvision": "0.29.0", "torchaudio": "2.11.0", "transformers": "4.57.6",
    "safetensors": "0.8.0", "numpy": "2.1.3", "pillow": "11.3.0", "huggingface-hub": "0.36.2",
    "pyarrow": "25.0.1",
}
# The kernel may import only the standard library and what hosted runtimes ship.
KERNEL_IMPORTS = {"ast", "hashlib", "importlib", "io", "json", "os", "platform", "re", "subprocess", "sys",
                  "time", "urllib", "zipfile", "pathlib", "IPython", "numpy", "PIL"}


def _notebook():
    return json.loads(NOTEBOOK.read_text(encoding="utf-8"))


def _code_cells():
    return [(c["id"], "".join(c["source"])) for c in _notebook()["cells"] if c["cell_type"] == "code"]


def _src(cid):
    return next(s for i, s in _code_cells() if i == cid)


def test_no_kernel_install_or_restart_guard():
    for cid, source in _code_cells():
        if cid == "uvcarrier":
            continue
        assert not re.search(r"-m\W+pip|^\s*[%!]\s*pip", source, re.M), cid
        for install in re.findall(r'"pip", "install"[^\n]*', source):
            assert '"--python", str(PYTHON)' in install, (cid, install)  # into the venv only
        for banned in ("Restart session", "sys.executable", "importlib.metadata", "check_call", "PINS"):
            assert banned not in source, (cid, banned)
    markdown = "\n".join("".join(c["source"]) for c in _notebook()["cells"] if c["cell_type"] == "markdown")
    assert "no restart" in markdown.lower() and "Linux x86_64 only" in markdown
    assert "Restart session" not in markdown and "restart-assisted" not in markdown


def test_kernel_imports_only_the_standard_library_and_hosted_packages():
    for cid, source in _code_cells():
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Import):
                names = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            for name in names:
                assert name.split(".")[0] in KERNEL_IMPORTS, (cid, name)


def test_lock_has_hashes_for_every_requirement_and_keeps_the_former_pins():
    text = LOCK.read_text(encoding="utf-8")
    hashed = r"((?:    --hash=sha256:[0-9a-f]{64}(?: \\)?\n)+)"
    blocks = re.findall(r"^([A-Za-z0-9_.-]+)==(\S+) \\\n" + hashed, text, re.M)
    pinned = {name.lower(): version for name, version, _ in blocks}
    requirement_lines = [ln for ln in text.splitlines() if re.match(r"^[A-Za-z0-9_.-]+==", ln)]
    assert len(blocks) == len(requirement_lines) >= 40
    for name, version in FORMER_PINS.items():
        assert pinned[name] == version, name
        assert f"{name} {version}" in text.split("# This file was autogenerated")[0], name
    direct = dict(ln.split("==") for ln in REQUIREMENTS.read_text(encoding="utf-8").splitlines()
                  if ln and not ln.startswith("#"))
    assert direct == FORMER_PINS
    assert "--python-platform x86_64-manylinux_2_28" in text and "--only-binary :all:" in text


def test_runtime_cell_pins_uv_and_installs_with_require_hashes_only_binary():
    source = _src(RUNTIME_CELL)
    assert '"--require-hashes", "--only-binary", ":all:"' in source
    assert "uv-0.12.15-py3-none-manylinux_2_17_x86_64" in source
    assert 'UV_SHA256 = "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60"' in source
    assert '"venv", "--clear", "--managed-python", "--python", "3.12.12"' in source
    assert 'platform.system() != "Linux" or platform.machine() != "x86_64"' in source
    assert 'ENV["MPLBACKEND"] = "Agg"' in source
    assert '("HF_TOKEN", "HUGGING_FACE_HUB_TOKEN", "PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP")' in source


def test_stages_run_with_the_venv_python_and_every_stage_is_called():
    source = _src(RUNTIME_CELL)
    assert 'PYTHON = ENV_ROOT / "bin" / "python"' in source
    assert 'command = [str(PYTHON), "-u", str(STAGE_SCRIPT), "--config"' in source
    assert 'STAGE_SCRIPT = RUNNER_ROOT / "ocr_workshop.py"' in source
    called = []
    for _, cell in _code_cells():
        called += re.findall(r'run_stage\(\s*"([a-z0-9-]+)"', cell)
    assert sorted(called) == sorted(stages.STAGES)  # each stage exactly once


def test_kernel_settings_are_the_stage_config_keys():
    tree = ast.parse(_src(RUNTIME_CELL))
    settings = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign)
                    and getattr(n.targets[0], "id", "") == "STAGE_SETTINGS")
    assert tuple(settings) == stages.CONFIG_KEYS
    config = {}
    exec(_src("d1171b39"), config)
    for name in settings:
        if name != "ENVIRONMENT":
            assert config[name] == getattr(stages, name), name  # stage defaults equal the notebook's


def test_model_libraries_are_used_only_by_the_stage_file():
    for cid, source in _code_cells():
        if cid == "uvcarrier":
            continue
        for library in ("torch", "transformers", "huggingface_hub", "safetensors", "pyarrow"):
            assert not re.search(rf"^\s*(import|from)\s+{library}\b", source, re.M), (cid, library)


def test_no_cell_line_is_longer_than_2000_characters():
    for cell in _notebook()["cells"]:
        for line in "".join(cell["source"]).splitlines():
            assert len(line) <= 2000, (cell["id"], len(line))


def test_carried_literals_are_pieces_of_at_most_1000_characters_equal_to_the_files():
    tree = ast.parse(_src("uvcarrier"))
    files = next(node.value for node in tree.body if isinstance(node, ast.Assign)
                 and node.targets[0].id == "CARRIED_FILES")
    for key, value in zip(files.keys, files.values, strict=True):
        name = ast.literal_eval(key)
        segment = ast.get_source_segment(_src("uvcarrier"), value)
        pieces = [ast.literal_eval(line.strip()) for line in segment.strip("()").splitlines() if line.strip()]
        assert pieces and all(len(piece) <= 1000 for piece in pieces), name
        assert "".join(pieces) == ast.literal_eval(value) == carrier.CARRIED[name].read_text(encoding="utf-8")


def test_carrier_pieces_split_long_lines():
    text = "a" * 2500 + "\nshort\n"
    parts = carrier.pieces(text)
    assert "".join(parts) == text and max(len(p) for p in parts) <= 1000


def test_carrier_cell_matches_the_tools_files():
    assert carrier.main(["--check"]) == 0
    carried = _notebook()["metadata"]["dimer"]["carried_files"]
    assert carried["ocr_workshop.py"]["sha256"] == hashlib.sha256(STAGE_FILE.read_bytes()).hexdigest()
    assert carried["requirements.lock.txt"]["sha256"] == hashlib.sha256(LOCK.read_bytes()).hexdigest()
    order = [c["id"] for c in _notebook()["cells"]]
    assert order.index("d1171b39") < order.index("uvcarrier") < order.index(RUNTIME_CELL)


def test_carrier_cell_writes_files_that_hash_to_the_lock(tmp_path):
    ns = {"WORK_DIR": str(tmp_path / "work")}
    exec(compile(_src("uvcarrier"), "uvcarrier", "exec"), ns)
    runner = tmp_path / "work" / "runner"
    assert (runner / "ocr_workshop.py").read_bytes() == STAGE_FILE.read_bytes()
    assert (runner / "requirements.lock.txt").read_bytes() == LOCK.read_bytes()


def test_uv_revision_is_logged_in_the_notebook_metadata():
    revisions = _notebook()["metadata"]["dimer"]["review_revisions"]
    entry = next(r for r in revisions if r["date"] == "2026-10-03")
    assert entry["change"] == "uv isolated environment" and entry["hosted_execution"] == "pending"
    assert entry["pins_changed"] == "none"


def test_docs_say_linux_x86_64_only():
    row = next(ln for ln in (ROOT / "tutorials" / "README.md").read_text(encoding="utf-8").splitlines()
               if NOTEBOOK.name in ln and ln.startswith("|"))
    assert "Linux x86_64 only" in row and "Candidate" in row
    verification = (ROOT / "docs" / "release-verification.md").read_text(encoding="utf-8")
    assert "2026-10-03 uv isolated environment" in verification


# ---- kernel <-> stage hand-off -----------------------------------------------------------------------------
def _kernel(tmp_path, shown):
    """The runtime cell's helpers, with this interpreter standing in for the isolated environment's."""
    tree = ast.parse(_src(RUNTIME_CELL))
    keep = {"show_block", "show_display", "run_stage", "read_json", "state", "belfort_split"}
    tree.body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in keep
                 or isinstance(n, ast.Assign) and getattr(n.targets[0], "id", "") in {"STAGE_SETTINGS",
                                                                                       "DISPLAY_MARKER"}]
    ns = {"json": json, "os": os, "re": re, "subprocess": subprocess, "Path": Path, "Image": Image,
          "Markdown": lambda text: ("markdown", text), "display": shown.append,
          "PYTHON": sys.executable, "STAGE_SCRIPT": STAGE_FILE, "WORK_ROOT": tmp_path / "work",
          "ENV": dict(os.environ, PYTHONIOENCODING="utf-8"), "ENVIRONMENT": {"kind": "test"}}
    exec(_src("d1171b39"), ns)
    ns.update(OUTPUT_DIR=str(tmp_path / "outputs"), WORK_DIR=str(tmp_path / "work"))
    (tmp_path / "work").mkdir()
    exec(compile(tree, RUNTIME_CELL, "exec"), ns)
    return ns


def test_run_stage_streams_output_and_renders_stage_displays(tmp_path, capsys):
    shown = []
    ns = _kernel(tmp_path, shown)
    ns["run_stage"]("pages")
    out = capsys.readouterr().out
    assert "Reference = every visible string in drawing order" in out and "notice: PUBLIC NOTICE" in out
    assert "\x1edimer-display" not in out  # display requests are rendered, not printed
    assert len(shown) == 1 and isinstance(shown[0], Image.Image) and shown[0].size == (1040, 370)
    pages = ns["state"]("pages.json")
    assert sorted(pages) == ["invoice", "notice", "report", "technical_note"]
    config = json.loads((tmp_path / "work" / "stage_config.json").read_text(encoding="utf-8"))
    assert config["ENVIRONMENT"] == {"kind": "test"} and config["WORK_DIR"] == str(tmp_path / "work")
    ns["show_display"]("\x1edimer-display " + json.dumps({"kind": "block", "title": "T", "body": "a ``` b"}))
    assert shown[-1] == ("markdown", "**T**\n\n````text\na ``` b\n````")


def test_a_failing_stage_raises_with_its_log(tmp_path, capsys):
    ns = _kernel(tmp_path, [])
    with pytest.raises(RuntimeError, match="compare failed with exit 1"):
        ns["run_stage"]("compare")  # no earlier stage has written its state
    assert "run the earlier cells of this notebook in order first" in capsys.readouterr().out


def test_belfort_split_reads_the_staged_line_images(tmp_path):
    ns = _kernel(tmp_path, [])
    state_dir = tmp_path / "work" / "state"
    state_dir.mkdir()
    split = {"splits": {"test": [{"id": "belfort-test-1", "text": "a"}]}}
    (state_dir / "belfort.json").write_text(json.dumps(split))
    line_dir = tmp_path / "work" / "belfort" / "test"
    line_dir.mkdir(parents=True)
    Image.new("RGB", (30, 10), (1, 2, 3)).save(line_dir / "belfort-test-1.png")
    [record] = ns["belfort_split"]("test")
    assert record["text"] == "a" and record["image"].getpixel((0, 0)) == (1, 2, 3)


def test_line_images_round_trip_losslessly(tmp_path, monkeypatch):
    monkeypatch.setattr(stages, "WORK_DIR", str(tmp_path / "work"))
    image = Image.fromarray(np.random.default_rng(0).integers(0, 256, (20, 50, 3), dtype=np.uint8), "RGB")
    split = {"train": [], "validation": [], "test": [{"id": "belfort-test-7", "image": image, "text": "x",
                                                      "source_row_group": 0}]}
    image_dir = stages.belfort_image_dir()
    image_dir.mkdir(parents=True)
    image.save(image_dir / "belfort-test-7.png")
    stages.save_state("belfort.json", {"image_digests": {"belfort-test-7": stages.image_digest(image)},
                                       "splits": {k: [{x: r[x] for x in ("id", "text", "source_row_group")}
                                                      for r in v] for k, v in split.items()}})
    [loaded] = stages.load_belfort_split("test", images=True)
    assert loaded["image"].tobytes() == image.tobytes()
    Image.new("RGB", (50, 20)).save(image_dir / "belfort-test-7.png")
    with pytest.raises(RuntimeError, match="differs from the verified sample"):
        stages.load_belfort_split("test", images=True)


def test_full_stage_sequence_with_model_doubles(tmp_path):
    from test_workshop_optional_paths import stage_ns

    ns = stage_ns(tmp_path)

    class Model:
        def parameters(self):
            return [types.SimpleNamespace(numel=lambda: 4)]

    def generate(*args):
        images = args[4]
        return [dict(text="PUBLIC NOTICE", doctags="<doctag><text>PUBLIC NOTICE</text></doctag>",
                     new_tokens=3, truncated=False, inference_seconds=0.1) for _ in images]

    ns.update(RUN_BELFORT=False, load_got=lambda: (Model(), None, 0, 1, 0.5),
              load_smoldoc=lambda: (Model(), None, 1, 0, 0.25), got_generate=generate, smol_generate=generate,
              RUNTIME={"device": "cpu"})
    ns["save_state"]("snapshots.json", {"got": {"dir": "g", "verify_seconds": 1.0},
                                        "smoldocling": {"dir": "s", "verify_seconds": 2.0}})
    ns["save_state"]("belfort.json", {"digest": "d", "image_digests": {}, "splits": {"test": []}})
    ns["save_state"]("baselines.json", {"empty_metrics": None, "constant_metrics": None, "constant_text": ""})
    for stage in ("pages", "got-load", "got-belfort", "got-pages", "got-probes", "smol-load", "smol-belfort",
                  "smol-pages", "smol-specialized", "smol-probes", "compare", "resources", "export", "byod",
                  "summary"):
        ns["STAGES"][stage]()
    out_root = tmp_path / "outputs"
    metrics = json.loads((out_root / "metrics.json").read_text(encoding="utf-8"))
    assert [r["parameters"] for r in metrics["resources"]] == [4, 4]
    assert len(metrics["rendered_pages"]) == 8 and len(metrics["shape_robustness"]) == 8
    provenance = json.loads((out_root / "provenance.json").read_text(encoding="utf-8"))
    assert provenance["runtime"] == {"device": "cpu"} and provenance["got"]["parameter_count"] == 4
    assert (out_root / "pages" / "notice" / "source.png").is_file()


def test_stage_command_line_rejects_unknown_stages(tmp_path):
    config = tmp_path / "config.json"
    config.write_text(json.dumps({"WORK_DIR": str(tmp_path / "work")}), encoding="utf-8")
    command = [sys.executable, str(STAGE_FILE), "--config", str(config), "--stage"]
    unknown = subprocess.run([*command, "train"], capture_output=True, text=True, timeout=60)
    assert unknown.returncode == 2 and "invalid choice" in unknown.stderr
    config.write_text(json.dumps({"WORK_DIR": "w", "EXTRA": 1}), encoding="utf-8")
    bad = subprocess.run([*command, "pages"], capture_output=True, text=True, timeout=60)
    assert bad.returncode == 1 and "unknown stage config keys: ['EXTRA']" in bad.stderr
