"""DIMER inference package for the pinned ``stepfun-ai/GOT-OCR-2.0-hf`` checkpoint."""

from .pipeline import (
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_MODE,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    MODES,
    STOP_STRING,
    GotOcr2Pipeline,
    character_error_rate,
    evaluation_report,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
    word_error_rate,
)

__all__ = [
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_MODE",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "MODES",
    "STOP_STRING",
    "GotOcr2Pipeline",
    "character_error_rate",
    "evaluation_report",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
    "word_error_rate",
]
